config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  # Root route for the landing page
  root to: "pages#home"

  # Route for the user dashboard
  get 'dashboard', to: 'pages#dashboard'

  # Resource routes for keyboards
  resources :keyboards, only: [:index, :show]

  # Other routes as needed
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :keyboard

  validates :keyboard_id, uniqueness: { scope: :user_id, message: "has already been favorited by the user" }
end

app/models/image.rb
class Image < ApplicationRecord
  belongs_to :user, optional: true
  belongs_to :keyboard, optional: true

  validates :url, presence: true
end

app/models/keyboard.rb
class Keyboard < ApplicationRecord
  belongs_to :user, optional: true
  has_many :keyboard_votes, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :images, dependent: :destroy

  TYPE_OPTIONS = ['Pre-Assembled', 'Custom'].freeze
  SWITCHES_OPTIONS = ['MX', 'Alps', 'Choc', 'Choc v2'].freeze
  LAYOUT_OPTIONS = ['Row stagger', 'Ortholinear', 'Column Stagger'].freeze

  validates :name, presence: true
  validates :keyboard_type, inclusion: { in: TYPE_OPTIONS }, allow_nil: true
  validates :switches, inclusion: { in: SWITCHES_OPTIONS }, allow_nil: true
  validates :layout, inclusion: { in: LAYOUT_OPTIONS }, allow_nil: true


  validates :wireless, :hot_swappable, :oled_compatible, :split, :open_source, inclusion: { in: [true, false] }
end

app/models/keyboard_vote.rb
class KeyboardVote < ApplicationRecord
  belongs_to :keyboard
  belongs_to :user

  validates :vote_type, presence: true, inclusion: { in: %w[upvote downvote] }

  validates :user_id, uniqueness: { scope: :keyboard_id, message: "has already voted for this keyboard"}
end

app/models/questionnaire_response.rb
class QuestionnaireResponse < ApplicationRecord
  belongs_to :user, optional: true
  serialize :responses, JSON

  validates :session_id, presence: true, unless: -> { user_id.present? }
  validates :user_id, presence: true, unless: -> { session_id.present? }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

         has_many :keyboards, dependent: :destroy
         has_many :keyboard_votes, dependent: :destroy
         has_many :questionnaire_responses, dependent: :destroy
         has_many :favorites, dependent: :destroy
         has_many :images, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/keyboards_controller.rb
class KeyboardsController < ApplicationController
  before_action :set_keyboard, only: [:show, :edit, :update, :destroy]

  def index
    @keyboards = Keyboard.all
  end

  def show
  end

  def new
    @keyboard = Keyboard.new
  end

  def edit
  end

  def create
    @keyboard = Keyboard.new(keyboard_params)

    if @keyboard.save
      redirect_to @keyboard, notice: 'Keyboard was successfully created.'
    else
      render :new
    end
  end

  def update
    if @keyboard.update(keyboard_params)
      redirect_to @keyboard, notice: 'Keyboard was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @keyboard.destroy
    redirect_to keyboards_url, notice: 'Keyboard was successfully destroyed.'
  end


  private
    def set_keyboard
      @keyboard = Keyboard.find(params[:id])
    end

    def keyboard_params
      params.require(:keyboard).permit(:name, :description, :type, :image_url, :user_id, :community_uploaded)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def dashboard
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/keyboards/index.html.erb
<% if false %>
<%= simple_form_for :search, url: keyboards_path, method: :get, html: { id: 'search-form' }, remote: true do |f| %>
  <%= f.input :query, as: :string, label: false, placeholder: "Search keyboards...", input_html: { value: params[:query] } %>

  <%= f.input :keyboard_type, collection: ['Pre-Assembled', 'Custom'], include_blank: true, selected: params[:keyboard_type], label: false %>
  <%= f.input :firmware, collection: ['QMK', 'ZMK', 'TMK', 'Proprietary'], include_blank: true, selected: params[:firmware], label: false %>
  <%= f.input :switches, collection: ['MX', 'Alps', 'Choc', 'Choc v2'], include_blank: true, selected: params[:switches], label: false %>
  <%= f.input :layout, collection: ['Row stagger', 'Ortholinear'], include_blank: true, selected: params[:layout], label: false %>
  <%= f.input :wireless, as: :boolean, selected: params[:wireless], label: 'Wireless?' %>
  <%= f.input :hot_swappable, as: :boolean, selected: params[:hot_swappable], label: 'Hot Swappable?' %>
  <%= f.input :oled_compatible, as: :boolean, selected: params[:oled_compatible], label: 'OLED Compatible?' %>
  <%= f.input :split, as: :boolean, selected: params[:split], label: 'Split?' %>
  <%= f.input :open_source, as: :boolean, selected: params[:open_source], label: 'Open Source?' %>

  <%= f.button :submit, "Search" %>
<% end %>
<% end %>
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8" />
        <link rel="stylesheet" href="globals.css" />
        <link rel="stylesheet" href="style.css" />
    </head>
    <body>
        <div class="gallery">
            <div class="div">
                <div class="logo">
                    <div class="overlap-group">
                        <p class="text-wrapper">O r g a n i c</p>
                        <div class="text-wrapper-2">keyboards</div>
                    </div>
                </div>
                <div class="horitzontal-menu">
                    <div class="text-wrapper-3">Profile</div>
                    <div class="text-wrapper-4">Gallery</div>
                    <img class="line" src="img/line-1.svg" />
                    <div class="text-wrapper-5">Data base</div>
                </div>
                <div class="overlap">
                    <div class="size">
                        <div class="overlap-2">
                            <div class="text-wrapper-6">Size</div>
                            <div class="overlap-group-2">
                                <div class="text-wrapper-7">+</div>
                                <img class="img" src="img/line-2-8.svg" />
                            </div>
                        </div>
                    </div>
                    <div class="controller">
                        <div class="overlap-2">
                            <div class="text-wrapper-6">Controller</div>
                            <div class="overlap-group-2">
                                <div class="text-wrapper-7">+</div>
                                <img class="img" src="img/line-2-6.svg" />
                            </div>
                        </div>
                    </div>
                    <div class="switches">
                        <div class="overlap-2">
                            <div class="text-wrapper-6">Switches</div>
                            <div class="overlap-group-2">
                                <div class="text-wrapper-7">+</div>
                                <img class="img" src="img/line-2-5.svg" />
                            </div>
                        </div>
                    </div>
                    <div class="keys-layout">
                        <div class="overlap-2">
                            <div class="text-wrapper-8">Keys layout</div>
                            <div class="overlap-group-2">
                                <div class="text-wrapper-7">+</div>
                                <img class="img" src="img/line-2-7.svg" />
                            </div>
                        </div>
                    </div>
                    <div class="layout">
                        <div class="overlap-2">
                            <div class="text-wrapper-6">Layout</div>
                            <div class="overlap-group-2">
                                <div class="text-wrapper-7">+</div>
                                <img class="img" src="img/line-2.svg" />
                            </div>
                        </div>
                    </div>
                    <div class="firmware">
                        <div class="overlap-2">
                            <div class="text-wrapper-6">Firmware</div>
                            <div class="overlap-group-2">
                                <div class="text-wrapper-7">+</div>
                                <img class="img" src="img/line-2-9.svg" />
                            </div>
                        </div>
                    </div>
                    <div class="bluetooth">
                        <div class="overlap-2">
                            <div class="text-wrapper-6">Bluetooth</div>
                            <div class="overlap-group-2">
                                <div class="text-wrapper-7">-</div>
                                <img class="img" src="img/line-2-2.svg" />
                            </div>
                        </div>
                    </div>
                    <div class="rectangle"></div>
                    <div class="rectangle-2"></div>
                    <div class="rectangle-3"></div>
                    <div class="clicked-box"><img class="icons-check" src="img/check.svg" /></div>
                    <div class="icons-check-wrapper"><img class="icons-check" src="img/check-2.svg" /></div>
                    <div class="img-wrapper"><img class="icons-check" src="img/image.svg" /></div>
                    <div class="vertical-filters">
                        <div class="filter">
                            <div class="overlap-3">
                                <div class="text-wrapper-6">Type</div>
                                <div class="overlap-group-2">
                                    <div class="text-wrapper-7">-</div>
                                    <img class="img" src="img/line-2-3.svg" />
                                </div>
                            </div>
                            <div class="text-wrapper-9">Any</div>
                            <div class="text-wrapper-10">Yes</div>
                            <div class="text-wrapper-11">Custom</div>
                            <div class="text-wrapper-12">No</div>
                            <div class="text-wrapper-13">Assembled</div>
                            <div class="text-wrapper-14">Vintage</div>
                        </div>
                        <div class="filter-2">
                            <div class="text-wrapper-6">Hotswappable</div>
                            <div class="text-wrapper-15">+</div>
                            <img class="line-2" src="img/line-2-4.svg" />
                        </div>
                    </div>
                </div>
                <div class="pics-gallery">
                    <img class="rectangle-4" src="img/rectangle-13.svg" />
                    <img class="rectangle-5" src="img/rectangle-17.svg" />
                    <img class="rectangle-6" src="img/rectangle-14.svg" />
                    <img class="rectangle-7" src="img/rectangle-18.svg" />
                    <img class="rectangle-8" src="img/rectangle-19.svg" />
                    <img class="rectangle-9" src="img/rectangle-12.svg" />
                    <img class="rectangle-10" src="img/rectangle-16.svg" />
                    <img class="rectangle-11" src="img/rectangle-20.svg" />
                    <img class="rectangle-12" src="img/rectangle-21.png" />
                </div>
                <div class="search-bar">
                    <div class="overlap-4">
                        <img class="icon-artwork" src="img/icon-artwork.svg" />
                        <div class="text-wrapper-16">Search...</div>
                    </div>
                </div>
            </div>
        </div>
    </body>
</html>

app/views/keyboards/show.html.erb
<%# app/views/keyboards/show.html.erb %>

<h1><%= @keyboard.name %></h1>


<% if @keyboard.images.any? %>
  <% @keyboard.images.each do |image| %>
    <img src="<%= image.url %>" alt="Keyboard Image">
  <% end %>
<% end %>

<div>
  <strong>Type:</strong> <%= @keyboard.keyboard_type %>
</div>

<div>
  <strong>Switches:</strong> <%= @keyboard.switches %>
</div>

<div>
  <strong>Layout:</strong> <%= @keyboard.layout %>
</div>

<div>
  <strong>Hot Swappable:</strong> <%= @keyboard.hot_swappable ? 'Yes' : 'No' %>
</div>

<div>
  <strong>Split:</strong> <%= @keyboard.split ? 'Yes' : 'No' %>
</div>

<div>
  <strong>OLED Compatible:</strong> <%= @keyboard.oled_compatible ? 'Yes' : 'No' %>
</div>

<div>
  <strong>Wireless:</strong> <%= @keyboard.wireless ? 'Yes' : 'No' %>
</div>

<div>
  <strong>Rows:</strong> <%= @keyboard.rows %>
</div>

<div>
  <strong>Columns:</strong> <%= @keyboard.columns %>
</div>

<div>
  <strong>Thumb Keys:</strong> <%= @keyboard.thumb_keys %>
</div>

<div>
  <strong>Github Repo Link:</strong> <%= link_to 'GitHub Repository', @keyboard.github_repo_link %>
</div>


<%= link_to 'Back to Keyboards', keyboards_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ErgoEmporium</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link href="https://fonts.googleapis.com/css2?family=Michroma&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@400;700&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Major+Mono+Display&display=swap" rel="stylesheet">
  </head>

  <body>
    <%= render "shared/flashes" %>
    <%= yield %>

  </body>
</html>

app/views/pages/home.html.erb
    <div class="home">
      <div class="div">
        <div class="logo">
          <div class="overlap-group">
            <p class="text-wrapper">O r g a n i c</p>
            <div class="text-wrapper-2">keyboards</div>
          </div>
        </div>
        <div class="survey-button">
          <div class="overlap"><div class="text-wrapper-3">Take the survey</div></div>
        </div>
        <div class="text-wrapper-4">Data base</div>
        <div class="text-wrapper-5">Gallery</div>
        <img class="line" src="img/line-1.svg" />
<%= image_tag 'foto_keyboard.png', class: 'foto-keyboard' %>
        <p class="p">A community-driven database of mechanical keyboard related information.</p>
        <div class="find-out-highlight">
          <div class="overlap-2">
            <div class="rectangle"></div>
            <div class="rectangle-2"></div>
            <p class="text-wrapper-6">Find out which one is perfect for you!</p>
          </div>
        </div>
        <button class="login-button">
          <div class="div-wrapper"><div class="text-wrapper-7">Login</div></div>
        </button>
      </div>
    </div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= alert %>
  </div>
<% end %>